version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000/api
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    env_file:
      - ./backend/.env.example
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata: 