"""添加用户偏好设置表

Revision ID: 97046c382b56
Revises: 3cdd80d45f77
Create Date: 2025-05-18 23:19:25.343231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97046c382b56'
down_revision = '3cdd80d45f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('vip_levels', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('monthly_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vip_levels', schema=None) as batch_op:
        batch_op.alter_column('monthly_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))

    op.drop_table('user_preferences')
    # ### end Alembic commands ###
